version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=historic_METAR
      - DB_USER=postgres
      - DB_PASSWORD=yourpassword
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: historic_METAR
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: